type: merge_anno
task_name: onepose_train_match
match_type: 'softmax'
split: 'val'

data_base_dir: 'dataset_local/OnePose'
gs_dir: 'output/anno_match/OnePose/val_data'
merge_output_dir: 'output/merged_anno'

val_use_last_n_seq: 1
names:
    # Val set
    - "0601"
    - "0602"
    - "0603"
    - "0604"
    #- "0605"
    - "0606"
    - "0607"
    - "0608"
    - "0609"
    - "0610"
    - "0611"
    - "0612"
    - "0613"
    - "0614"
    - "0615"
    - "0616"
    - "0617"
    - "0618"
    - "0619"
    - "0620"
    - "0621"

network:
    detection: loftr
    matching: loftr

datamodule:
    data_dir: ${data_base_dir}/val_data
    gs_dir: ${gs_dir}

    out_path: ${merge_output_dir}/${task_name}/${split}.json