type: merge_anno
task_name: onepose_train_match
match_type: 'softmax'
split: 'train'

data_base_dir: 'dataset_local/OnePose'
gs_dir: 'output/anno_match/OnePose/train_data'
merge_output_dir: 'output/merged_anno'

names:
    # Train Set
    - '0410'
    - '0413'
    - '0414'
    - '0415'  #*** 0.88  重建不好
    - '0416'    #0.70
    # - '0418'  # 0
    - '0420'
    - '0421'
    - '0443'   # 重建效果不好 0.46
    - '0445'   # 重建效果不好 0.74
    - '0448'   #0.87
    - '0460'   #0.48
    - '0461'  #0.82
    - '0462'
    - '0463' # 点太多了  0.145
    - '0464'
    - '0465'
    - '0477'  #0.86
    - '0479'
    - '0484'
    - '0499'  #0.91
    - '0506'
    - '0507'
    - '0509'   # buhao 0.75
    - '0512'  #0.84
    - '0513'
    - '0516'
    - '0529'  #0.6
    - '0530'  #0.59
    - '0531'  #0.7
    - '0532' #0.78
    - '0533' 
    # - '0536'  #0.4
    - '0542'
    - '0545'  # 0.74
    # - '0546' #重建效果不好 0.07
    # - '0549' #重建效果不好 0.31
    - '0556'
    # - '0561' #重建效果不好 0.069
    - '0562'
    - '0563' 
    - '0566' #重建效果一般 0.68
    - '0567'  # 0.75
    # - '0569'   #0.48
    - '0571'  #0.84
    - '0572'
    # - '0573'  #0.29
    # - '0574' #重建效果不好 0.03
    # - '0575'  #0.31

network:
    detection: loftr
    matching: loftr

datamodule:
    data_dir: ${data_base_dir}
    gs_dir: ${gs_dir}

    out_path: ${merge_output_dir}/${task_name}/${split}.json
